version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password' 
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306" 

  usuarios:
    build:
      context: ./usuarios
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    restart: always
      
  productos:
    build:
      context: ./productos
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - db

  ordenes:
    build:
      context: ./ordenes
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - usuarios
      - productos
      - db 

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8082:80"
volumes:
  mysql-data:
